name: brick_bootstrap5_plus
description: A Flutter UI Dart libraries with the bootstrap5.
version: 1.1.0
repository: https://github.com/onecodeman2017/brick_bootstrap5_plus

environment:
  sdk: '>=3.6.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  intersperse: ^2.0.0
  intl: ^0.20.2
  tinycolor2: ^3.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
